Settings:
  Prefix: '&e&lEnchantments: ' #The prefix in the msgs
  InvName: '&f&lPURCHASE ENCHANTMENTS:' #The name of the /CE inventory
  GUISize: 45 #The size of the GUI, Must be a factor of 9
  Clouds: True #Enable and Disable the Clouds for the Wings Enchantment
  EnchantmentBookLore:
    - '&aSuccess Rate: &f%Success_Rate%%'
    - '&cDestroy Rate: &f%Destroy_Rate%%'
    - '&7Drag and drop on item to enchant it'
  LostBook:
    Item: '340'
    Name: '&c&lABANDONED BOOK'
    Lore:
      - '&4&lWARNING: &7These enchantments are not setup yet.'
      - '&7When you click these books it gives you tier 3 enchant books'
      - '&7No point in wasting money'
      - '&a&lCOMING SOON: &7August 17th 2016'
  ProtectionCrystal:
    InGUI: true #If its in the GUI.
    Slot: 13 #Slot it is in
    Item: '399' #Item it is
    Glowing: True #If it is enchanted
    Protected: '&f&lANCIENT PROTECTED'
    Name: '&c&lAncient Protection Orb' #Name of the item
    Lore: #Lore of the item
      - '&e&l(!) &7A rare crystal that is said to'
      - '&e&l(!) &7protect items from getting lost'
      - '&e&l(!) &7while the owners away in the after life.'
      - ''
      - '&e&l(!) &7Drag and drop on an item.'
    GUIName: '&c&l&nAncient Protection Orb'
    GUILore:
      - '&e&l(!) &7A rare crystal that is said to'
      - '&e&l(!) &7protect items from getting lost'
      - '&e&l(!) &7while the owners away in the after life.'
      - ''
      - '&6Cost: &e&n$75000'
  BlackSmith: #Options for the Black Smith
    InGUI: true #In the GUI.
    Slot: 15 #Slot it is in.
    Item: '263' #Item that shows in the GUI
    Glowing: False #Is it enchanted
    Name: '&e&l(!) &b&lBlack Smith' #Name of the Item in the GUI
    Lore: #Lore on the item.
      - '&e&l(!) &7Use the black smith here.'
    GUIName: '&e&l(!) &b&lBlack Smith' #Name of the Black Smith's GUI
    Results:
      None: '&c&lNo Results' #Name of the item when there are no results in the Black Smith
      Found: '&c&lCost: &6&l%Cost%XP' #The lore at the bottom of the item
    Transaction: #Options for the pricing
      Money/XP: XP #Costs XP or Money
      Lvl/Total: Lvl #Uses Total xp or xp Levels
      Costs: #Cost options
        Power-Up: 5 #When a enchantment levels up 1 on an item
        Add-Enchantment: 3 #When it adds an enchantment to the item from another item
        Book-Upgrade: 5 #Leveling up a books power
  Tinker: #Settings for Info item in the GUI
    InGUI: true #Toggle whether it is in the /CE GUI or not
    Slot: 32 #Slot it is in
    Item: '386' #Item it is
    Glowing: True #Whether it glows like its enchanted
    Name: '&e&l(!) Tinkerer' #Name of the Item
    Lore: #Lore of the item
      - '&7Tinker the books you dont want'
      - '&7For Sucess & Destroy Dusts'
  Dust: #Settings for the Magical Dust
    MysteryDust:
      Item: '385' #Item mystery dust is
      Name: '&b&lMyserty Dust' #Name of the dust
      Lore: #Use %Percent% to set the percent
        - '&7Chance to receive a random dust'
        - '&7Success Dust & Destroy Dust'
    SuccessDust:
      InGUI: false #If you can buy it in the /CE Gui
      GUIName: '&a&lSuccess Dust' #Name of the item in the GUI
      GUILore: #Lore in the GUI.
        - '&eCost: &a&l$50'
        - '&7Dust allows you to bring'
        - '&7Up your &aSuccess Rate'
      Slot: 4 #Slot number it is in
      Item: '353' #Item the dust is
      Name: '&aMagical Angel Dust' #Name of the dust
      Lore: #Lore for the dust
        - '&a+%Percent%% Success Rate'
        - '&7Apply to an Enchantment Book to'
        - '&7Increase the Success Rate by &e%Percent%%'
      PercentRange: #Range the success rate will be.
        Max: 30 #Max percent
        Min: 5 #Minimum percent
    DestroyDust:
      InGUI: false #If you can buy it in the /CE Gui
      GUIName: '&c&lDestroy Dust' #Name of the item in the GUI
      GUILore: #Lore in the GUI.
        - '&eCost: &a&l$50'
        - '&7Dust allows you to bring'
        - '&7Down your &4Destroy Rate'
      Slot: 6 #Slot number it is in
      Item: '353' #Item the dust is
      Name: '&eMagical Fixing Dust' #Name of the dust
      Lore: #Lore for the dust
        - '&c-%Percent%% Destroy Rate'
        - '&7Apply to an Enchantment Book to'
        - '&7Decrease the Destroy Rate by &e%Percent%%'
      PercentRange: #Range the destroy rate will be.
        Max: 10 #Max percent
        Min: 2 #Minimum percent
  Info: #Settings for Info item in the GUI
    InGUI: True #Toggle whether it is in the /CE GUI or not
    Slot: 41 #Slot it is in
    Item: '395' #Item it is
    Glowing: True #Whether it glows like its enchanted
    Name: '&f&lENCHANTMENTS' #Name of the Item
    Lore: #Lore of the item
      - '&7List of all enchantments.'
  Info2: #Settings for Info2 item in the GUI
    InGUI: True #Toggle whether it is in the /CE GUI or not
    Slot: 14 #Slot it is in
    Item: '395' #Item it is
    Glowing: True #Whether it glows like its enchanted
    Name: '&aEnchantment list' #Name of the Item
    Lore: #Lore of the item
      - '&7Cl'
  BlackScroll: #Settings for the Black Scrolls
    Item: '339' #The item the Black Scroll can be
    Name: '&f&l* &f&lBlack Scroll &f&l*' #The name of the Black Scroll
    InGUI: True #Toggle being able to buy in the /CE Gui. Cost is controlled in the SignOptions section
    GUIName: '&f&l* &f&lBlack Scroll &f&l*'
    Slot: 33 #Slot you can buy the scroll at
    Lore: #Lore of the item in the GUI
      - '&e&l(!) &e&lLeft click to purchase a &6Blackscroll'
      - ''
      - '&a&lCOST: &7$100,000'
    SuccessChance: #Controls what the success chance will be when they get the book from the Black Scroll
      Max: 75 #The Max percent
      Min: 35 #The Minimum percent
    DestroyChance: #Controls what the destroy chance will be when they get the book from the Black Scroll
      Max: 25 #The Max percent
      Min: 5 #The Minimum percent
  WhiteScroll:
    Item: '339' #The item the white scroll is.
    Name: '&f&l* &f&lWhite Scroll &f&l*' #The name of the white scrolls.
    InGUI: true #Toggle being able to buy in the /CE Gui. Cost is controlled in the SignOptions section
    GUIName: '&f&l* &f&lWhite Scroll &f&l*'
    Slot: 31 #Slot you can buy the scroll at
    Lore: #Lore of the scroll in the GUI
      - '&e&l(!) &e&lLeft click to purchase a &6Whitescroll'
      - ''
      - '&a&lCOST: &7$100,000'
    ProtectedName: '&b&lPROTECTED' #The lore that is added to protect an item.
  EnchantmentOptions: #Options for enchanted books.
    MaxAmountOfEnchantmentsToggle: True #Turn on an off the Max amount of enchantments
    IncludeVanillaEnchantments: False #Count Vanilla enchantments also?
  SignOptions: #Options for the Signs.
    ProtectionCrystalStyle: 
      Cost: 75000 #How much to buy it
      Money/XP: Money #Use money or xp
      Lvl/Total: XP #If using xp you can choose to use Lvls or Total xp
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&5&lProtection &b&lCrystal'
      Line4: '&c&lCost: &a&l$1000'
      Buy-Message: '&7You have just bought a &5&lProtection &b&lCrystal.' #Message when buying an item.
    SuccessDustStyle: 
      Cost: 50 #How much to buy a Magical Dust
      Money/XP: Money #Use money or xp
      Lvl/Total: XP #If using xp you can choose to use Lvls or Total xp
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Angel Dust'
      Line4: '&c&lCost: &a&l$50'
      Buy-Message: '&7You have just bought a &aMagical Angel Dust&7.'
    DestroyDustStyle: 
      Cost: 50 #How much to buy a Magical Dust
      Money/XP: Money #Use money or xp
      Lvl/Total: XP #If using xp you can choose to use Lvls or Total xp
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Fixing Dust'
      Line4: '&c&lCost: &a&l$50'
      Buy-Message: '&7You have just bought a &eMagical Fixing Dust&7.'
    CategoryShopStyle: #What the sign will look like. The price will be determined by the category you pick
      Line1: '&b&lCrazy Enchant' #Line 1 of the sign
      Line2: '&b&lShop:' #Line 2 of the sign
      Line3: '&2&l%Category%' #Line 3 of the sign
      Line4: '&c&lCost: &6&l%Cost%XP' #Line 4 of the sign
      Buy-Message: '&7You have just bought an &8Custom Enchantment Book&7.'
    BlackScrollStyle: 
      Cost: 100000 #How much to buy a black scroll
      Money/XP: Money #Use money or xp
      Lvl/Total: XP #If using xp you can choose to use Lvls or Total xp
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&4&lBlack &8&lScrolls'
      Line4: '&c&lCost: &a&l$50'
      Buy-Message: '&7You have just bought a &8&l&nBlack Scroll&7.'
    WhiteScrollStyle:
      Cost: 100000
      Money/XP: Money
      Lvl/Total: XP
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&f&lWhite &b&lScrolls'
      Line4: '&c&lCost: &a&l$50'
      Buy-Message: '&7You have just bought a &e&lWhite Scroll&7.'
  GUICustomization: #This allows you to customize unclickable items into you GUI.
    - 'Slot:1, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:2, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:3, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:4, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:5, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:6, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:7, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:8, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:9, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:10, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:11, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:12, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:13, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:14, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:15, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:16, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:17, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:18, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:19, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:20, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:22, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:24, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:26, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:27, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:28, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:29, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:30, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:31, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:32, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:33, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:34, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:35, Item:160:7, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:36, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:37, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:38, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:39, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:40, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:41, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:42, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:43, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:44, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    - 'Slot:45, Item:160:0, Name:&b&l(!) &7You have &b&n{XP} XP'
    
Categories: #You can make as many different categories as you want
  T1: #Name of the category
    Name: '&e&lBASIC &8» &7Costs &f&n15&7 Levels.' #Name in the GUI
    Slot: 21 #The Slot number the item will be in
    Lore: #The lore of the Item
      - '&e&l(!) &e&lLeft click to buy a &6Basic &e&lenchantment book'
    Item: '340' #The id for the item
    Money/XP: XP #Can be either Money or XP that players can use to by books
    Lvl/Total: Lvl #You can choose Lvl or Total, Lvl uses XP lvls and Total uses the total XP the player has
    Cost: 15 #How much the Books cost
    LostBook: #Controls the Lost Book shop for this tier
      InGUI: False #If it shows in the /CE Gui
      Slot: 1 #Slot it will be in
      Item: '340' #The item that is showen in the GUI
      Glowing: False #Is it enchanted
      Name: '&8&l&nLost&c&l Tier1 &8&l&nBooks' #Name of the item
      Lore: #Lore on the item
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier1 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$1000'
      Money/XP: Money #Costs money or XP
      Lvl/Total: Lvl #If XP then Levels or Total XP
      Cost: 15 #The Price of the book
    EnchOptions: #Enchantment Options
      SuccessPercent: #The range for the success rate that the enchantment will have
        Max: 90 #The max success rate
        Min: 5 #The min success rate
      DestroyPercent: #The range for the destroy rate that the enchantment will have
        Max: 50 #The max destroy rate
        Min: 4 #The min destroy rate
      MaxLvlToggle: True #Turn on and off Max Level cap
      LvlRange: #The range of lvls that can be found in the Category.
        Max: 2
        Min: 1
  T2:
    Name: '&b&lRARE &8» &7Costs &f&n30&7 Levels.'
    Slot: 23
    Lore:
      - '&e&l(!) &e&lLeft click to buy a &6Rare &e&lenchantment book'
    Item: '340'
    Money/XP: XP
    Lvl/Total: Lvl
    Cost: 30
    LostBook:
      InGUI: false
      Slot: 2
      Item: '340'
      Glowing: False
      Name: '&8&l&nLost&c&l Tier2 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier2 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$2000'
      Money/XP: Money
      Lvl/Total: Lvl
      Cost: 30
    EnchOptions:
      SuccessPercent:
        Max: 90
        Min: 5
      DestroyPercent:
        Max: 50
        Min: 4
      MaxLvlToggle: True
      LvlRange:
        Max: 3
        Min: 2
  T3:
    Name: '&6&lMYTHICAL &8» &7Costs &f&n45&7 Levels.'
    Slot: 25
    Lore:
      - '&e&l(!) &e&lLeft click to buy a &6Mythical &e&lenchantment book'
    Item: '340'
    Money/XP: XP
    Lvl/Total: Lvl
    Cost: 45
    LostBook:
      InGUI: true
      Slot: 14
      Item: '340'
      Glowing: True
      Name: '&f&l* &c&lAbandoned Tier III Books &f&l*'
      Lore:
        - '&7These books have been lost for centuries'
        - '&7They were said to be never found on &b&nVialia Planet&7'
        - '&7They have been coming up alot lately on this planet'
        - '&7Do you have enough to purchase one of these books?'
        - ''
        - '&a&lCOMING SOON: &7August 17th 2016'
        - ''
        - '&cRarity: &75'
        - '&7Books left: &623'
        - '&7Cost: &6$120k'
        - ''
        - '&bPLANET: &7Vialia'
      Money/XP: Money
      Lvl/Total: Lvl
      Cost: 125000
    EnchOptions:
      SuccessPercent:
        Max: 90
        Min: 5
      DestroyPercent:
        Max: 50
        Min: 4
      MaxLvlToggle: True
      LvlRange:
        Max: 3
        Min: 3